declare const styles: {
    readonly card: string;
    readonly cardDescription: string;
    readonly cardGrid: string;
    readonly cardLink: string;
    readonly cardTitle: string;
    readonly heroActionButton: string;
    readonly heroActions: string;
    readonly heroBanner: string;
    readonly heroContent: string;
    readonly heroGrid: string;
    readonly heroLiveBadges: string;
    readonly heroPanel: string;
    readonly heroPanelLogo: string;
    readonly heroSubtitle: string;
    readonly heroTitle: string;
    readonly liveBadgeAnchor: string;
    readonly liveBadgeImage: string;
    readonly liveBadgeList: string;
    readonly liveBadgeListItem: string;
    readonly mainContent: string;
};
export = styles;
