/**
 * @packageDocumentation
 * Sidebar structure for developer documentation (`docs/docusaurus/site-docs`).
 */

import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars = {
    docs: [
        {
            className: "sb-dev-overview",
            id: "intro",
            label: "🏁 Developer overview",
            type: "doc",
        },
        {
            className: "sb-dev-started",
            id: "getting-started",
            label: "🚀 Local workflow",
            type: "doc",
        },
        {
            className: "sb-dev-typedoc",
            collapsed: false,
            items: [
                {
                    id: "typedoc-pipeline",
                    label: "TypeDoc pipeline",
                    type: "doc",
                },
                {
                    id: "api-reference",
                    label: "API reference",
                    type: "doc",
                },
            ],
            label: "TypeDoc integration",
            type: "category",
        },
        {
            className: "sb-dev-tooling",
            collapsed: false,
            items: [
                {
                    id: "inspectors",
                    label: "Inspector workflows",
                    type: "doc",
                },
                {
                    href: "https://nick2bad4u.github.io/eslint-plugin-typedoc/eslint-inspector/",
                    label: "ESLint Inspector output",
                    type: "link",
                },
                {
                    href: "https://nick2bad4u.github.io/eslint-plugin-typedoc/stylelint-inspector/",
                    label: "Stylelint Inspector output",
                    type: "link",
                },
            ],
            label: "Tooling outputs",
            type: "category",
        },
        {
            className: "sb-dev-api",
            collapsed: true,
            items: [
                {
                    dirName: "developer/api",
                    type: "autogenerated",
                },
            ],
            label: "Generated TypeDoc API",
            type: "category",
        },
    ],
} satisfies SidebarsConfig;

export default sidebars;
